src/IOT_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('device.urls', namespace='device'))
]

src/device/urls.py
from django.urls import path
from . import views

app_name = 'device'

urlpatterns = [
    path('', views.index, name='device'),
    path('envir/', views.envindex, name='device'),
    path('post/', views.postbot, name='device'),
    path('auto/', views.autoindex, name='device'),
    path('api/', views.change_io_state, name='submit_prediction'),
    # path('autoapi/', views.change_io_state, name='submit_prediction'),
    path('sensorapi/', views.add_data_from_iot_device, name='update'),
    path('io/<str:device_id>', views.get_io_state, name='state'),
    path('envir/sensor/<str:device_id>', views.get_sensor_state, name='sensor'),
]

src/device/models.py
from django.db import models
from django.db.models.fields import BooleanField, CharField, FloatField, IntegerField, TimeField
import uuid

# Create your models here.


class Device(models.Model):
    Device_ID = CharField(max_length=100)
    name = CharField(max_length=100)
    state = BooleanField()
    fig = CharField(max_length=300)
    descriptuin = CharField(max_length=100, default='關閉')

    def __str__(self):
        return self.name


# class fan(models.Model):
#     Device_ID = CharField(max_length=100, default=uuid.uuid4())
#     name = CharField(max_length=100)
#     fig = CharField(max_length=300)
#     state = BooleanField(default=0)
#     descriptuin = CharField(max_length=100, default='關閉')

#     def __str__(self):
#         return self.name


# class AirConditioner(models.Model):
#     Device_ID = CharField(max_length=100, default=uuid.uuid4())
#     fig = CharField(max_length=300)
#     name = CharField(max_length=100)
#     state = BooleanField(default=0)
#     temp = FloatField(default=0)
#     humidity = FloatField(default=0)
#     control_temp = IntegerField(default=0)
#     descriptuin = CharField(max_length=100, default='關閉')

#     def __str__(self):
#         return self.name


# class other(models.Model):
#     Device_ID = CharField(max_length=100, default=uuid.uuid4())
#     fig = CharField(max_length=300)
#     name = CharField(max_length=100)
#     state = BooleanField(default=0)
#     descriptuin = CharField(max_length=100, default='關閉')

#     def __str__(self):
#         return self.name

class Sensor(models.Model):
    Device_ID = CharField(max_length=200)
    name = CharField(max_length=100)
    value = FloatField(default=0)
    fig = CharField(max_length=300)

    def __str__(self):
        return self.name


class scene(models.Model):
    SceneName = CharField(max_length=200)
    OpenDevice_ID = CharField(max_length=100)
    closeDevice_ID = CharField(max_length=100)

    def __str__(self):
        return self.SceneName


class automation(models.Model):
    automation_name = CharField(max_length=200)
    sensor_condition = CharField(max_length=200)
    OpenDevice_ID = CharField(max_length=100)
    closeDevice_ID = CharField(max_length=100)
    Enable = BooleanField()

    def __str__(self):
        return self.automation_name


class timer(models.Model):
    timer_name = CharField(max_length=200)
    time = TimeField()
    OpenDevice_ID = CharField(max_length=100)
    closeDevice_ID = CharField(max_length=100)
    Enable = BooleanField()

    def __str__(self):
        return self.timer_name

src/device/views.py
from django.contrib.auth.models import User
from django.http import response, HttpResponse, JsonResponse
from django.shortcuts import render
from .models import *  # Device, Sensor, scene  # light, fan, AirConditioner, other
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

import json
import os


def autoindex(request):
    autodata = automation.objects.all()
    timerdata = timer.objects.all()
    return render(request, 'auto.html', { 'autodata': autodata, 'timerdata': timerdata})

def postbot(request):
    return render(request, 'postbot.html')

def get_io_state(request, device_id):
    if request.method == 'GET':
        try:
            choose = Device.objects.get(Device_ID=device_id)
        except:
            response = json.dumps(
                [{'Error': 'No device with that ID'}])
            return HttpResponse(response, content_type='text/json')
        response = json.dumps(
            [{'Device_ID': choose.Device_ID, 'state': choose.state}])
    return JsonResponse({'Device_ID': choose.Device_ID, 'state': choose.state}, safe=False)

@csrf_exempt
def add_data_from_iot_device(request):
    if request.method == 'POST':
        try:
            payload = json.loads(request.body)
            print(payload)
            DEVICEID = payload['DEVICE_ID']
            VALUE = float(payload['VALUE'])
            print(DEVICEID, VALUE)
        except:
            DEVICEID = str(request.POST.get('DEVICE_ID'))
            VALUE = float(request.POST.get('VALUE'))
            print(DEVICEID, VALUE)
        try:
            choose = Sensor.objects.get(Device_ID=DEVICEID)
        except:
            response = json.dumps([{'Error': 'Data could not be added!'}])
            return HttpResponse(response, content_type='text/json')
        # print(choose)
        # print("old", choose.value)
        choose.value = VALUE
        choose.save()
        # print("new", choose.value)
        # response = json.dumps([{'Success': 'Data added successfully!'}])
    return JsonResponse({'DEVICE_ID': DEVICEID, 'VALUE': VALUE}, safe=False)

def get_sensor_state(request, device_id):
    if request.method == 'GET':
        try:
            choose = Sensor.objects.get(Device_ID=device_id)
        except:
            response = json.dumps(
                [{'Error': 'No device with that ID'}])
            return HttpResponse(response, content_type='text/json')
    return JsonResponse({'Device_ID': choose.Device_ID, 'value': choose.value}, safe=False)


def index(request):
    lightdata = Device.objects.order_by('name')[:]
    scenedata = scene.objects.all()
    autodata = automation.objects.all()
    timerdata = timer.objects.all()

    return render(request, 'his.html', {"lightdata": lightdata,  'scenedata': scenedata, 'autodata': autodata, 'timerdata': timerdata})


def envindex(request):
    sensordata = Sensor.objects.order_by('name')[:]
    # fandata = fan.objects.all()
    # AirConditionerdata = AirConditioner.objects.all()
    # otherdata = other.objects.all()
    # scenedata = scene.objects.all()

    return render(request, 'env.html', {"sensordata": sensordata})


def realtimechange(request):
    lightdata = Device.objects.all()
    # fandata = fan.objects.all()
    # AirConditionerdata = AirConditioner.objects.all()
    # otherdata = other.objects.all()
    return HttpResponse({"lightdata": lightdata})


def change_io_state(request):
    if request.POST.get('action') == 'post':
        DEVICEID = request.POST.get('DEVICE_ID')
        STATUS = request.POST.get('STATUS')
        DES = "關閉"
        if STATUS == 'false':
            STATUS = bool("")
            DES = "關閉"
        else:
            STATUS = bool("1")
            DES = "開啟"
        try:
            choose = Device.objects.get(Device_ID=DEVICEID)
        except:
            return JsonResponse({'Status': "尚未註冊此物件"}, safe=False)
            # try:
            #     choose = fan.objects.get(Device_ID=DEVICEID)
            # except:
            #     try:
            #         choose = AirConditioner.objects.get(
            #             Device_ID=DEVICEID)
            #     except:
            #         try:
            #             choose = other.objects.get(
            #                 Device_ID=DEVICEID)

        print(choose)
        # test1 = light.objects.get(id=DEVICEID)
        print("old", choose.state)
        choose.state = STATUS
        choose.descriptuin = DES
        choose.save()
        print("new", choose.state)
        return JsonResponse({'Status': STATUS}, safe=False)

# def 

src/device/templates/auto.html
{% extends "base.html" %}

{% block main %}
{% csrf_token %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- <h1>SmartMT</h1> -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">控制中心<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/envir">環境感測<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/auto">自動化<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

<div class="container pt-5">
    <div class="row">

        <h1>自動化</h1>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">名稱</th>
                    <th scope="col">條件</th>
                    <th scope="col">開啟裝置ID</th>
                    <th scope="col">關閉裝置ID</th>
                    <th scope="col">啟用</th>
                    <th scope="col">更新</th>
                </tr>
            </thead>
            <tbody>
                {% for data in autodata %}
                <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>
                        <input type="number" step="0.1" class="form-control" id="automation_name"
                            placeholder="{{data.automation_name}}" required>
                    </td>
                    <td>
                        <input type="number" step="0.1" class="form-control" id="sensor_condition"
                            placeholder="{{data.sensor_condition }}" required>
                    </td>
                    <td>
                        <input type="number" step="0.1" class="form-control" id="OpenDevice_ID"
                            placeholder="{{data.OpenDevice_ID }}" required>
                    </td>
                    <td>
                        <input type="number" step="0.1" class="form-control" id="closeDevice_ID"
                            placeholder="{{data.closeDevice_ID }}" required>
                    <td>
                        <label class="switch">
                            {% if data.Enable == True %}
                            <input id=auto{{ data.id }} type="checkbox" onchange="handleClick(this)" checked>
                            <span class="slider round"></span>
                            {%else%}
                            <input id=auto{{ data.id }} type="checkbox" onchange="handleClick(this)">
                            <span class="slider round"></span>
                            {% endif %}
                        </label>
                    </td>
                    <td>
                        <div class="form-group">
                            <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal"
                                data-target="#exampleModal" style='align-items: center;'>Update</button>
                        </div>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>

<script>

    function handleClick(cb) {
        $.ajax({
            url: '{% url "device:submit_prediction" %}',
            type: "POST",
            dataType: 'text',

            data: {
                DEVICE_ID: cb.id,
                STATUS: cb.checked,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success: function (json) {
                var response = JSON.parse(json);
                name = cb.id + 'd'
                if (response.Status == true) {
                    document.getElementById(name).innerHTML = "開啟";
                } else {
                    document.getElementById(name).innerHTML = "關閉";
                }
                // console.log('{% url "device:submit_prediction" %}')
                // document.getElementById(cb.id).checked = true;
            },
            error: function (xhr, errmsg, err) {
                console.log("no no")
                document.getElementById(cb.id).checked = false;
            }
        });
        // console.log("Clicked, new value = " + cb.id + " " + cb.checked);
    }
</script>
{% endblock %}

src/device/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="icon" type="image/png"
        href="http://blog.inspiredled.com/wp-content/uploads/2017/08/apple-homekit-logo.png" />
    <title>Smart Home Kit</title>
</head>

<body>




    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
<style>
    /* The switch - the box around the slider */
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

    /* Hide default HTML checkbox */
    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    /* The slider */
    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked+.slider {
        background-color: #2196F3;
    }

    input:focus+.slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked+.slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

    .slider.round:before {
        border-radius: 50%;
    }

    .card {
        /* Add shadows to create the "card" effect */
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        transition: 0.3s;
        border-radius: 15px;
        margin: 15px;
        background: inherit;
        backdrop-filter: blur(15px);
        /* width: 200px; */
        /* 5px rounded corners */
    }


    /* On mouse-over, add a deeper shadow */
    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
    }

    /* Add some padding inside the card container */
    .container {
        padding: 2px 16px;
    }

    #floatingBarsG {
        position: relative;
        width: 17px;
        height: 21px;
        margin: auto;
        float: right;
    }

    .blockG {
        position: absolute;
        background-color: rgb(255, 255, 255);
        width: 3px;
        height: 7px;
        border-radius: 2px 2px 0 0;
        -o-border-radius: 2px 2px 0 0;
        -ms-border-radius: 2px 2px 0 0;
        -webkit-border-radius: 2px 2px 0 0;
        -moz-border-radius: 2px 2px 0 0;
        transform: scale(0.4);
        -o-transform: scale(0.4);
        -ms-transform: scale(0.4);
        -webkit-transform: scale(0.4);
        -moz-transform: scale(0.4);
        animation-name: fadeG;
        -o-animation-name: fadeG;
        -ms-animation-name: fadeG;
        -webkit-animation-name: fadeG;
        -moz-animation-name: fadeG;
        animation-duration: 1.2s;
        -o-animation-duration: 1.2s;
        -ms-animation-duration: 1.2s;
        -webkit-animation-duration: 1.2s;
        -moz-animation-duration: 1.2s;
        animation-iteration-count: infinite;
        -o-animation-iteration-count: infinite;
        -ms-animation-iteration-count: infinite;
        -webkit-animation-iteration-count: infinite;
        -moz-animation-iteration-count: infinite;
        animation-direction: normal;
        -o-animation-direction: normal;
        -ms-animation-direction: normal;
        -webkit-animation-direction: normal;
        -moz-animation-direction: normal;
    }

    #rotateG_01 {
        left: 0;
        top: 8px;
        animation-delay: 0.45s;
        -o-animation-delay: 0.45s;
        -ms-animation-delay: 0.45s;
        -webkit-animation-delay: 0.45s;
        -moz-animation-delay: 0.45s;
        transform: rotate(-90deg);
        -o-transform: rotate(-90deg);
        -ms-transform: rotate(-90deg);
        -webkit-transform: rotate(-90deg);
        -moz-transform: rotate(-90deg);
    }

    #rotateG_02 {
        left: 2px;
        top: 3px;
        animation-delay: 0.6s;
        -o-animation-delay: 0.6s;
        -ms-animation-delay: 0.6s;
        -webkit-animation-delay: 0.6s;
        -moz-animation-delay: 0.6s;
        transform: rotate(-45deg);
        -o-transform: rotate(-45deg);
        -ms-transform: rotate(-45deg);
        -webkit-transform: rotate(-45deg);
        -moz-transform: rotate(-45deg);
    }

    #rotateG_03 {
        left: 7px;
        top: 1px;
        animation-delay: 0.75s;
        -o-animation-delay: 0.75s;
        -ms-animation-delay: 0.75s;
        -webkit-animation-delay: 0.75s;
        -moz-animation-delay: 0.75s;
        transform: rotate(0deg);
        -o-transform: rotate(0deg);
        -ms-transform: rotate(0deg);
        -webkit-transform: rotate(0deg);
        -moz-transform: rotate(0deg);
    }

    #rotateG_04 {
        right: 2px;
        top: 3px;
        animation-delay: 0.9s;
        -o-animation-delay: 0.9s;
        -ms-animation-delay: 0.9s;
        -webkit-animation-delay: 0.9s;
        -moz-animation-delay: 0.9s;
        transform: rotate(45deg);
        -o-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        -webkit-transform: rotate(45deg);
        -moz-transform: rotate(45deg);
    }

    #rotateG_05 {
        right: 0;
        top: 8px;
        animation-delay: 1.05s;
        -o-animation-delay: 1.05s;
        -ms-animation-delay: 1.05s;
        -webkit-animation-delay: 1.05s;
        -moz-animation-delay: 1.05s;
        transform: rotate(90deg);
        -o-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        -webkit-transform: rotate(90deg);
        -moz-transform: rotate(90deg);
    }

    #rotateG_06 {
        right: 2px;
        bottom: 2px;
        animation-delay: 1.2s;
        -o-animation-delay: 1.2s;
        -ms-animation-delay: 1.2s;
        -webkit-animation-delay: 1.2s;
        -moz-animation-delay: 1.2s;
        transform: rotate(135deg);
        -o-transform: rotate(135deg);
        -ms-transform: rotate(135deg);
        -webkit-transform: rotate(135deg);
        -moz-transform: rotate(135deg);
    }

    #rotateG_07 {
        bottom: 0;
        left: 7px;
        animation-delay: 1.35s;
        -o-animation-delay: 1.35s;
        -ms-animation-delay: 1.35s;
        -webkit-animation-delay: 1.35s;
        -moz-animation-delay: 1.35s;
        transform: rotate(180deg);
        -o-transform: rotate(180deg);
        -ms-transform: rotate(180deg);
        -webkit-transform: rotate(180deg);
        -moz-transform: rotate(180deg);
    }

    #rotateG_08 {
        left: 2px;
        bottom: 2px;
        animation-delay: 1.5s;
        -o-animation-delay: 1.5s;
        -ms-animation-delay: 1.5s;
        -webkit-animation-delay: 1.5s;
        -moz-animation-delay: 1.5s;
        transform: rotate(-135deg);
        -o-transform: rotate(-135deg);
        -ms-transform: rotate(-135deg);
        -webkit-transform: rotate(-135deg);
        -moz-transform: rotate(-135deg);
    }



    @keyframes fadeG {
        0% {
            background-color: rgb(0, 0, 0);
        }

        100% {
            background-color: rgb(255, 255, 255);
        }
    }

    @-o-keyframes fadeG {
        0% {
            background-color: rgb(0, 0, 0);
        }

        100% {
            background-color: rgb(255, 255, 255);
        }
    }

    @-ms-keyframes fadeG {
        0% {
            background-color: rgb(0, 0, 0);
        }

        100% {
            background-color: rgb(255, 255, 255);
        }
    }

    @-webkit-keyframes fadeG {
        0% {
            background-color: rgb(0, 0, 0);
        }

        100% {
            background-color: rgb(255, 255, 255);
        }
    }

    @-moz-keyframes fadeG {
        0% {
            background-color: rgb(0, 0, 0);
        }

        100% {
            background-color: rgb(255, 255, 255);
        }
    }
</style>

</html>

src/device/templates/dashboard.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>控制面板</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Theme style -->
    <link rel="stylesheet"
        href="https://adminlte.io/themes/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/dist/css/AdminLTE.min.css">

</head>

<body>
    <div class="wrapper">
        <!-- Main content -->
        <p class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-sm-3">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{ user_count }}</h3>

                            <p>用户总数</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-sm-3">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>{{ task_count }}</h3>
                            <p>任务总数</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-sm-3">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{ user_count }}</h3>

                            <p>用户总数</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-sm-3">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>{{ task_count }}</h3>

                            <p>任务总数</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="#" class="small-box-footer">更多信息 <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
        </div>
        </p>
    </div>
</body>

src/device/templates/env.html
{% extends "base.html" %}

{% block main %}
{% csrf_token %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- <h1>SmartMT</h1> -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">控制中心<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/envir">環境感測<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/auto">自動化<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

<div class="container pt-0">
    <div class="row">
        {% for result in sensordata %}
        <div class="col">
            <div class="card">
                <img src={{ result.fig }} alt="Avatar" style="width:50px;margin: 15px; margin-bottom: 30px;">
                <div class="container">
                    <p>{{ result.name }}</p>
                    <!-- <p id={{ result.Device_ID }}d>{{ result.descriptuin}}</p> -->
                    <h1 id={{ result.Device_ID }}>{{ result.value }}</h1>
                    </label>
                </div>
            </div>
            </td>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    setInterval(() => {
        "{% for result in sensordata %}"
        $.ajax({
            url: 'sensor/' + '{{ result.Device_ID }}',
            type: 'get',
            success: function (json) {
                document.getElementById("{{ result.Device_ID }}").innerHTML = json.value;
            }
        });
        "{% endfor %}"
    }, 1000);
</script>
{% endblock %}

src/device/templates/postbot.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">AI analysis Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Input:</h5>
                <div>Device ID: <span id="rdeviceid"></span></div>
                <div>Value: <span id="rvalue"></span></div>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-7">
            <h2 style="margin-bottom: 40px;">Sensor update test</h2>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <!-- <label for="PID">ID</label> -->
                    <input type="text" step="0.1" class="form-control" id="DEVICEID" placeholder="Device ID" required>
                </div>
                <div class="form-group">
                    <!-- <label for="PID">ID</label> -->
                    <input type="number" step="0.1" class="form-control" id="VALUE" placeholder="Value" required>
                </div>
                <div class="form-group">
                    <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal"
                        data-target="#exampleModal" style='align-items: center;'>Update</button>
                </div>

            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "device:update" %}',
            data: {
                DEVICE_ID: $('#DEVICEID').val(),
                VALUE: $('#VALUE').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success: function (json) {
                console.log(json)
                document.forms["post-form"].reset();
                document.getElementById("rdeviceid").innerHTML = json.DEVICE_ID
                document.getElementById("rvalue").innerHTML = json.VALUE
            },
            error: function (xhr, errmsg, err) {
                console.log("no no")
            }
        });
    })
</script>

{% endblock %}